language: generic

env:
  global:
  - ACCESS_LEVEL=sandbox
  - LDC_RELEASE=1.0.0
  - LDC_VERSION=ldc2-${LDC_RELEASE}-${TRAVIS_OS_NAME}-x86_64
  - DOCKER_IMAGE=lomereiter/centos-ldc
  - secure: blVtZH4Ia+4MkeTm0gRwL07r/bzhVRJJjUEbtvt0pIQNAtDq5aYuKnCI9sIw99XmEbv9+tSLc6DXq9d6LrDDR0EG7UUB4sTP6XW1XNJXm/kLIuoOCxTnVk6WBHZ4jusMWE0MNNDVmIS8nHrpoDp2ERXbfasD/9GT+3avVUvnsMg=
  - secure: Kzdt/6PLGBhD5f8yOPaPdX5yxHisCPvmfYEKUcEVksKOEurQoIpsNjzAky/yzso4R21T6xycjawFvDXvlVA83m/WJZSDDiFLZVgGoaMoZl9UYOPESeZlJR57/HkjgCss0iz/AX9abUzJ1jGfRt9ujtwcoXB15PqUhbjk2iHF0f0=
  - secure: K0J2r5R8xQMlAUwCaPVWHZUO4U+c+czK6H9bnN5RZPYs5BXpYjdV7/RgkOHsN9b+UksFx7LQRstgcVVcC+mQJRV8slGrx/GSmIA93Dp2mskU9eR1aQjxcUK10VMbIQI6qbXsZvvRSWPirNDQY4s3CjEKEv34t2IGALTkwaU1NmI=
  - secure: J1ta2/K8lj5dbHRvk+jTUAMICSnepfyc8ILCfM/HFCRaXMJQJTX1HDzEMwK3tAzzKaKEp9Tbm2b3IwE1tCtFaAfYUGozmHLirkFfKqCu/jNUkxL807M8NiqMx+H7tu2aR6t9opYyBjNhtuthbIdir3c42nldYdpse0ZLhzQTLfs=

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz libconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L "https://github.com/ldc-developers/ldc/releases/download/v${LDC_RELEASE}/${LDC_VERSION}.tar.xz" | tar Jx; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$(pwd)/${LDC_VERSION}/bin:${PATH}; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LIBRARY_PATH=$(pwd)/${LDC_VERSION}/lib:${LIBRARY_PATH}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; docker run -dit --name linux -v $PWD:/build:z $DOCKER_IMAGE; fi

install:
  - wget https://github.com/craigcitro/r-travis/raw/master/scripts/dropbox.sh
  - chmod +x dropbox.sh
  - curl -L "https://dl.dropboxusercontent.com/u/7916095/shunit2-2.0.3.tgz" | tar zx

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make sambamba-ldmd2-64 && ./.run_tests.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec linux bash -c "cd /build; make sambamba-ldmd2-64 && ./.run_tests.sh"; fi

after_success:
  - tar cjvf sambamba_${TRAVIS_OS_NAME}.tar.bz2 ./build/sambamba
  - ./dropbox.sh upload sambamba_${TRAVIS_OS_NAME}.tar.bz2
